#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width        5
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_width         0.5
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill /usr/share/wallpapers/p1C5/netBlue.jpg

$HOME/./.config/polybar/b5PWm-p@ly.sh
picom --experimental-backends --config $HOME/.config/picom/picom.conf &

xsetroot -cursor_name left_ptr &
setxkbmap es # set your keayboard leyout Ex:
